name: "commit-status-updater"
description: "A simple Github Action that allows us to update the status of the last commit in a pull request"
author: "Rob"
branding:
  icon: "check-circle"
  color: "purple"
inputs:
  token:
    description: >
      Auth token used to add status commits.
    default: "${{ github.token }}"
    required: true
  url:
    description: >
      URL for the status check.
    default: ""
  description:
    description: >
      Description for the status check.
    default: ""
  name:
    description: >
      The context for the status. Default is GithubActions - ${GITHUB_WORKFLOW}
    default: "GithubActions - ${{ github.workflow }}"
    required: true
  status:
    description: >
      Commit or job status, based on this the action will set the correct status in the commit:
      Accepted values are: 'error', 'failure', 'pending', 'success' and 'cancelled'.
